#!/bin/bash

# get repo name
gitrepo=${PWD##*/}
repo=${gitrepo%.*}
cd "../live/$repo" \
&& echo "checkout master" \
&& git --git-dir="../../$gitrepo" --work-tree="." checkout master -f \
&& pwd \
&& sh deploy.sh
